<a href="https://colab.research.google.com/github/kssuny/sjcu-python/blob/main/A4_SunnyKim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read SAS data
sales = pd.read_sas("sales.sas7bdat",encoding = "utf-8")
demographic = pd.read_sas("demographic_id.sas7bdat",encoding = "utf-8")
survey2 = pd.read_sas("survey2.sas7bdat",encoding = "utf-8")
inventory = pd.read_sas("inventory.sas7bdat",encoding = "utf-8")

# Problem 1
p1 = sales[sales["EmpID"].isin(["9888","0177"])]
print("\nProblem 1")
display(p1)

# Problem 2

p2 = sales[((sales["Region"] == "North") & (s["Quantity"]<60)) | (sales["Customer"] == "Pet's are Us")]
print("\nProblem 2")
display(p2)

# Problem 3
demographic["ID"] = demographic["ID"].astype(str).str.lstrip("0")
survey2["ID"] = survey2["ID"].astype(int).astype(str)

merged_data = pd.merge(demographic, survey2, on="ID", how="inner")
print("\nProblem 3")
display(merged_data)

# Problem 4

NewPrices.loc[NewPrices["Model"].isin(["M567", "X999"]), "Price"] = [25.95, 35.99]
print("\nProblem 4")
NewPrices

Problem 1

   EmpID            Name Region           Customer  Item  Quantity  UnitCost  TotalSales
5   0177  Glenda Johnson   East     Food Unlimited  188X     100.0      6.99       699.0
6   0177  Glenda Johnson   East      Shop and Drop  144L     100.0      8.99       899.0
8   9888       Sharon Lu   West      Cost Cutter's   122      50.0      5.99       299.5
9   9888       Sharon Lu   West       Pet's are Us  100W    1000.0      1.99      1990.0
12  0177  Glenda Johnson  North      Minimart Inc.   777       5.0     10.50        52.5
13  0177  Glenda Johnson   East  Barco Corporation   733       2.0  10000.00     20000.0

Problem 2

   EmpID            Name Region           Customer  Item  Quantity  UnitCost  TotalSales
0   1843    George Smith  North  Barco Corporation  144L      50.0      8.99       449.5
2   1843    George Smith  North      Minimart Inc.  188S       3.0   5199.00     15597.0
3   1843    George Smith  North  Barco Corporation  908X       1.0   5129.00      5129.0
9   9888       Sharon Lu   West       Pet's are Us  100W    1000.0      1.99      1990.0
12  0177  Glenda Johnson  North      Minimart Inc.   777       5.0     10.50        52.5
14  1843    George Smith  North      Minimart Inc.  188S       3.0   5199.00     15597.0

Problem 3

  ID        DOB Gender   Q1   Q2   Q3   Q4   Q5
0  1 2037-10-10      M  1.0  3.0  5.0  4.0  2.0
1  2 1987-07-12      F  5.0  5.0  4.0  4.0  3.0
2  4 2000-01-05      M  3.0  5.0  1.0  4.0  2.0
3  5 1966-06-04      F  5.0  4.0  5.0  4.0  5.0

Problem 4

  Model   Price
0  M567   25.95
1  S888   12.99
2  L776  159.98
3  X999   35.99
4  M123    4.59
5  S776    1.99